trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.1'
  displayName: 'Use Node.js 10.15.1'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run compile
  displayName: 'Compile client'

- script: |
    npm run test
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'util/junit.xml'
    testRunTitle: 'Run unit tests'

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-navigation-int'
    githubServiceConnection: Microsoft
    languages: typescript
    nugetFeed: 'https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices-staging/nuget/v3/index.json'
    serviceEndpoint: 'https://int.richcodenav.vsengsaas.visualstudio.com'
