trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.1'
  displayName: 'Use Node.js 10.15.1'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run compile
  displayName: 'Compile client'

- script: |
    npm run test
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'util/junit.xml'
    testRunTitle: 'Run unit tests'

- script: |
    mkdir testSetup
    cd testSetup
    git clone https://github.com/microsoft/vscode-languageserver-node.git
    cd vscode-languageserver-node
    npm install
    npm run symlink
    cd jsonrpc
    node ../../../tsc/lib/main.js -p ./tsconfig.json --outputFormat=line --out=jsonrpc.lsif
